// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file's observable state. `name` is the basename (top level, non-recursive),
 * the row identity the frontend keys on. Serialized as a `{ kind, ... }` union.
 *
 * This enum is the SINGLE SOURCE OF TRUTH for the IPC payload: `ts-rs` derives the
 * matching TS `FileDelta` into `src/lib/bindings/FileDelta.ts` (run `cargo test`
 * after changing the variants), so the frontend imports it instead of hand-mirroring
 * it. `notify_debouncer_full` and `Channel` carry it; `serde` and `ts-rs` read the
 * same `tag`/`rename_all`, so the wire shape and the generated type stay in lockstep
 * by construction.
 */
export type FileDelta = { "kind": "content", name: string, text: string, } | { "kind": "removed", name: string, } | { "kind": "unreadable", name: string, };
