// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A vault root's observable shape. `tables` are the immediate child directories, each one a
 * table. `root_has_table_files` is true when the root itself has files that belong inside a table
 * folder (`matter.json` or `.md`), so the UI can distinguish an empty vault from a table folder
 * opened at the wrong altitude.
 */
export type VaultMembership = { tables: Array<string>, rootHasTableFiles: boolean, };
