// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';

/** Commands */
export const commands = {
	/**
	 *  Writes text at the cursor position using the clipboard sandwich technique
	 *
	 *  This method preserves the user's existing clipboard content by:
	 *  1. Saving the current clipboard content
	 *  2. Writing the new text to clipboard
	 *  3. Simulating a paste operation (Cmd+V on macOS, Ctrl+V elsewhere)
	 *  4. Restoring the original clipboard content
	 *
	 *  This approach is faster than typing character-by-character and preserves
	 *  the user's clipboard, making it ideal for inserting transcribed text.
	 */
	writeText: (text: string) =>
		typedError<null, string>(__TAURI_INVOKE('write_text', { text })),
	/**
	 *  Simulates pressing the Enter/Return key
	 *
	 *  This is useful for automatically submitting text in chat applications
	 *  after transcription has been pasted.
	 */
	simulateEnterKeystroke: () =>
		typedError<null, string>(__TAURI_INVOKE('simulate_enter_keystroke')),
	getCurrentRecordingId: () =>
		typedError<string | null, string>(
			__TAURI_INVOKE('get_current_recording_id'),
		),
	enumerateRecordingDevices: () =>
		typedError<string[], string>(__TAURI_INVOKE('enumerate_recording_devices')),
	initRecordingSession: (
		deviceIdentifier: string,
		recordingId: string,
		sampleRate: number | null,
	) =>
		typedError<null, string>(
			__TAURI_INVOKE('init_recording_session', {
				deviceIdentifier,
				recordingId,
				sampleRate,
			}),
		),
	closeRecordingSession: () =>
		typedError<null, string>(__TAURI_INVOKE('close_recording_session')),
	startRecording: () =>
		typedError<null, string>(__TAURI_INVOKE('start_recording')),
	/**
	 *  Stop the recorder, write the canonical WAV artifact to
	 *  `<appDataDir>/recordings/{id}.wav`, return the small JSON handle.
	 *
	 *  JS never sees raw PCM samples on the wire: later operations look the
	 *  file up by id (`transcribe_recording`, `encode_recording_for_upload`,
	 *  `delete_recording`).
	 */
	stopRecording: () =>
		typedError<RecordingArtifact, string>(__TAURI_INVOKE('stop_recording')),
	cancelRecording: () =>
		typedError<null, string>(__TAURI_INVOKE('cancel_recording')),
	/**
	 *  Delete an artifact by id. Idempotent: a missing file is not an error
	 *  so the JS side can call this without first checking existence.
	 */
	deleteRecording: (recordingId: string) =>
		typedError<null, string>(
			__TAURI_INVOKE('delete_recording', { recordingId }),
		),
	/**
	 *  Canonical transcribe-by-id path. Resolves the audio file under
	 *  `<appDataDir>/recordings/{recordingId}.*` (cpal-written WAV,
	 *  navigator-saved webm/opus/mp4, etc.), decodes, runs inference using
	 *  the ambient configuration pushed via `set_transcription_config`.
	 *
	 *  Returns `NoConfig` if the FE has not pushed a config yet.
	 */
	transcribeRecording: (recordingId: string) =>
		typedError<string, TranscriptionError>(
			__TAURI_INVOKE('transcribe_recording', { recordingId }),
		),
	/**
	 *  Push the ambient transcription configuration. Replaces the per-call
	 *  `config` argument that `transcribe_recording` used to take.
	 *
	 *  Drift in `(engine, modelPath)` triggers a background preload so the
	 *  next `transcribe_recording` call does not pay cold-start latency.
	 *  Other field changes take effect on the next transcription with no
	 *  reload.
	 */
	setTranscriptionConfig: (config: TranscriptionConfig) =>
		__TAURI_INVOKE<void>('set_transcription_config', { config }),
	/**
	 *  Snapshot the current model state. Used by late-mounted observers to
	 *  catch up to the current lifecycle state without waiting for the next
	 *  event on `transcription://model-state`.
	 */
	getTranscriptionState: () =>
		__TAURI_INVOKE<LocalModelState>('get_transcription_state'),
	/**
	 *  Execute a command and wait for it to complete.
	 *
	 *  Parses the command string into program and arguments, then executes directly
	 *  without using a shell wrapper.
	 */
	executeCommand: (command: string) =>
		typedError<CommandOutput, string>(
			__TAURI_INVOKE('execute_command', { command }),
		),
	deleteFilesInDirectory: (
		directory: string,
		selection: DeleteFilesSelection,
	) =>
		typedError<number, string>(
			__TAURI_INVOKE('delete_files_in_directory', { directory, selection }),
		),
	writeMarkdownFiles: (directory: string, files: MarkdownFile[]) =>
		typedError<null, string>(
			__TAURI_INVOKE('write_markdown_files', { directory, files }),
		),
};

/* Types */
export type CommandOutput = {
	code: number | null;
	signal: number | null;
	stdout: string;
	stderr: string;
};

export type DeleteFilesSelection =
	| { kind: 'filenames'; filenames: string[] }
	| { kind: 'extension'; extension: string };

export type MarkdownFile = {
	filename: string;
	content: string;
};

export type RecordingArtifact = {
	id: string;
	durationMs: number;
	byteLength: number;
	mimeType: string;
};

/** Local transcription engine. Wire tags match the frontend
 *  `transcription.service` enum.
 */
export type Engine = 'whispercpp' | 'parakeet' | 'moonshine';

/** How long after the last transcription the resident model should be
 *  dropped. Mirrors the frontend `transcription.localModelUnloadPolicy`
 *  device setting.
 */
export type UnloadPolicy =
	| 'never'
	| 'immediately'
	| 'after_5_minutes'
	| 'after_30_minutes';

/** Ambient configuration the frontend pushes once per change. */
export type TranscriptionConfig = {
	engine: Engine;
	modelPath: string;
	language?: string | null;
	initialPrompt?: string | null;
	unloadPolicy: UnloadPolicy;
};

/** Lifecycle state of the resident model. */
export type ModelStatus =
	| { kind: 'idle' }
	| { kind: 'switching' }
	| { kind: 'loading' }
	| { kind: 'ready' }
	| { kind: 'inferring' }
	| { kind: 'error'; message: string };

/** Snapshot of everything observable about the resident model. */
export type LocalModelState = {
	engine: Engine | null;
	modelPath: string | null;
	status: ModelStatus;
};

/** Reason the resident model was dropped. */
export type UnloadReason =
	| { kind: 'immediate' }
	| { kind: 'idle'; idleSecs: number }
	| { kind: 'config_changed' };

/** Single event type for everything observable about the model lifecycle.
 *  Broadcast on the `transcription://model-state` Tauri event channel.
 */
export type ModelStateEvent =
	| { kind: 'loading_started'; state: LocalModelState }
	| {
			kind: 'loading_completed';
			state: LocalModelState;
			elapsedMs: number;
	  }
	| { kind: 'loading_failed'; state: LocalModelState; error: string }
	| { kind: 'inference_started'; state: LocalModelState }
	| {
			kind: 'inference_completed';
			state: LocalModelState;
			elapsedMs: number;
	  }
	| { kind: 'inference_failed'; state: LocalModelState; error: string }
	| { kind: 'unloaded'; state: LocalModelState; reason: UnloadReason }
	| { kind: 'selection_changed'; state: LocalModelState };

export type TranscriptionError =
	| { name: 'AudioReadError'; message: string }
	| { name: 'GpuError'; message: string }
	| { name: 'ModelLoadError'; message: string }
	| { name: 'TranscriptionError'; message: string }
	| { name: 'NoConfig'; message: string }
	| { name: 'ConfigError'; message: string };

/* Tauri Specta runtime */
async function typedError<T, E>(
	result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
	try {
		return { status: 'ok', data: await result };
	} catch (e) {
		if (e instanceof Error) throw e;
		return { status: 'error', error: e as any };
	}
}
