// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Writes text at the cursor position using the clipboard sandwich technique
	 * 
	 *  This method preserves the user's existing clipboard content by:
	 *  1. Saving the current clipboard content
	 *  2. Writing the new text to clipboard
	 *  3. Simulating a paste operation (Cmd+V on macOS, Ctrl+V elsewhere)
	 *  4. Restoring the original clipboard content
	 * 
	 *  This approach is faster than typing character-by-character and preserves
	 *  the user's clipboard, making it ideal for inserting transcribed text.
	 */
	writeText: (text: string) => typedError<null, string>(__TAURI_INVOKE("write_text", { text })),
	/**
	 *  Simulates pressing the Enter/Return key
	 * 
	 *  This is useful for automatically submitting text in chat applications
	 *  after transcription has been pasted.
	 */
	simulateEnterKeystroke: () => typedError<null, string>(__TAURI_INVOKE("simulate_enter_keystroke")),
	getCurrentRecordingId: () => typedError<string | null, string>(__TAURI_INVOKE("get_current_recording_id")),
	enumerateRecordingDevices: () => typedError<string[], string>(__TAURI_INVOKE("enumerate_recording_devices")),
	initRecordingSession: (deviceIdentifier: string, recordingId: string, sampleRate: number | null) => typedError<null, string>(__TAURI_INVOKE("init_recording_session", { deviceIdentifier, recordingId, sampleRate })),
	closeRecordingSession: () => typedError<null, string>(__TAURI_INVOKE("close_recording_session")),
	startRecording: () => typedError<null, string>(__TAURI_INVOKE("start_recording")),
	/**
	 *  Stop the recorder, write the canonical WAV artifact to
	 *  `<appDataDir>/recordings/{id}.wav`, return the small JSON handle.
	 * 
	 *  JS never sees raw PCM samples on the wire: later operations look the
	 *  file up by id (`transcribe_recording`, `encode_recording_for_upload`,
	 *  `delete_recording`).
	 */
	stopRecording: () => typedError<RecordingArtifact, string>(__TAURI_INVOKE("stop_recording")),
	cancelRecording: () => typedError<null, string>(__TAURI_INVOKE("cancel_recording")),
	/**
	 *  Delete an artifact by id. Idempotent: a missing file is not an error
	 *  so the JS side can call this without first checking existence.
	 */
	deleteRecording: (recordingId: string) => typedError<null, string>(__TAURI_INVOKE("delete_recording", { recordingId })),
	/**
	 *  Canonical transcribe-by-id path. Resolves the audio file under
	 *  `<appDataDir>/recordings/{recordingId}.*` (cpal-written WAV,
	 *  navigator-saved webm/opus/mp4, etc.), decodes, runs inference. This
	 *  is the single entry point for every local transcription call: cpal
	 *  stop, navigator/VAD/file-upload (after the pipeline saves), retry,
	 *  history replay.
	 */
	transcribeRecording: (recordingId: string, config: TranscribeRequest) => typedError<string, TranscriptionError>(__TAURI_INVOKE("transcribe_recording", { recordingId, config })),
	/**
	 *  Update the model unload policy from the frontend. Called by an effect
	 *  in the SvelteKit layout whenever `transcription.localModelUnloadPolicy`
	 *  changes, and once at app startup to push the initial value.
	 * 
	 *  Unknown values fall back to the default inside `UnloadPolicy::from_wire`
	 *  rather than erroring, so a future rename or corrupt localStorage value
	 *  never breaks transcription.
	 */
	setUnloadPolicy: (policy: string) => __TAURI_INVOKE<void>("set_unload_policy", { policy }),
	/**
	 *  Send a SIGINT signal to a process by PID.
	 *  This is equivalent to Ctrl+C and allows graceful shutdown.
	 */
	sendSigint: (pid: number) => __TAURI_INVOKE<SignalResult>("send_sigint", { pid }),
	/**
	 *  Execute a command and wait for it to complete.
	 * 
	 *  Parses the command string into program and arguments, then executes directly
	 *  without using a shell wrapper. This approach provides:
	 *  - Consistent behavior across all platforms
	 *  - No shell injection vulnerabilities
	 *  - Lower process overhead
	 *  - PATH resolution still works via Command::new()
	 * 
	 *  On Windows, also uses CREATE_NO_WINDOW flag to prevent console window flash (GitHub issue #815).
	 * 
	 *  # Arguments
	 *  * `command` - The command to execute as a string
	 * 
	 *  # Returns
	 *  Result containing the command output (stdout, stderr, exit code) or error message
	 * 
	 *  # Examples
	 *  ```ignore
	 *  execute_command("uname -a".to_string()).await?;
	 *  execute_command("git --version".to_string()).await?;
	 *  ```
	 */
	executeCommand: (command: string) => typedError<CommandOutput, string>(__TAURI_INVOKE("execute_command", { command })),
	/**
	 *  Spawn a child process without waiting for it to complete.
	 * 
	 *  Parses the command string into program and arguments, then spawns directly
	 *  without using a shell wrapper. This approach provides:
	 *  - Consistent behavior across all platforms
	 *  - No shell injection vulnerabilities
	 *  - Lower process overhead
	 *  - PATH resolution still works via Command::new()
	 * 
	 *  On Windows, also uses CREATE_NO_WINDOW flag to prevent console window flash (GitHub issue #815).
	 * 
	 *  # Arguments
	 *  * `command` - The command to spawn as a string
	 * 
	 *  # Returns
	 *  Result containing the process ID or error message
	 * 
	 *  # Examples
	 *  ```ignore
	 *  // Long-running process (e.g., a sidecar daemon)
	 *  spawn_command("my-sidecar --listen 127.0.0.1:9000".to_string()).await?;
	 *  ```
	 */
	spawnCommand: (command: string) => typedError<number, string>(__TAURI_INVOKE("spawn_command", { command })),
	/**
	 *  Reads all markdown files from a directory in parallel.
	 *  Uses Rayon for parallel I/O.
	 * 
	 *  # Arguments
	 *  * `directory_path` - Absolute path to the directory containing .md files
	 */
	readMarkdownFiles: (directoryPath: string) => typedError<string[], string>(__TAURI_INVOKE("read_markdown_files", { directoryPath })),
	/**
	 *  Counts markdown files in a directory without reading their contents.
	 * 
	 *  # Arguments
	 *  * `directory_path` - Absolute path to the directory containing .md files
	 */
	countMarkdownFiles: (directoryPath: string) => typedError<number, string>(__TAURI_INVOKE("count_markdown_files", { directoryPath })),
	/**
	 *  Deletes files inside a directory by filename.
	 *  Validates filenames are single path components (no traversal).
	 *  Uses Rayon for parallel deletion. Silently skips missing files.
	 * 
	 *  # Arguments
	 *  * `directory` - Absolute path to the directory containing the files
	 *  * `filenames` - Array of leaf filenames to delete
	 */
	deleteFilesInDirectory: (directory: string, filenames: string[]) => typedError<number, string>(__TAURI_INVOKE("delete_files_in_directory", { directory, filenames })),
	/**
	 *  Writes markdown files to disk atomically using a temporary file plus persist.
	 *  Validates all filenames upfront\u2014no files are written if any name is invalid.
	 * 
	 *  # Arguments
	 *  * `directory` - Absolute path to the output directory
	 *  * `files` - Array of `{ filename, content }` pairs to write
	 * 
	 *  # Returns
	 *  * `Ok(())` - All files written successfully
	 *  * `Err(String)` - Error if any write fails (earlier files may already be on disk)
	 */
	writeMarkdownFiles: (directory: string, files: MarkdownFile[]) => typedError<null, string>(__TAURI_INVOKE("write_markdown_files", { directory, files })),
};

/* Types */
export type CommandOutput = {
	code: number | null,
	signal: number | null,
	stdout: string,
	stderr: string,
};

export type MarkdownFile = {
	filename: string,
	content: string,
};

/**
 *  Wire representation of the subset of Moonshine variants the app surfaces.
 *  `transcribe-rs` exposes more variants but the UI only offers Tiny and Base.
 */
export type MoonshineVariantWire = "tiny" | "base";

/**
 *  Serializable handle returned to the JS side. The id is the lookup key
 *  for every later operation; the rest is metadata the UI needs without
 *  having to read the file (duration for analytics, byteLength for upload
 *  size, mimeType for the player).
 * 
 *  `mime_type` is `String` rather than `&'static str` so specta's TS
 *  generator sees a stable serializable shape (and so future producers,
 *  e.g. navigator-saved webm artifacts after the next collapse, can set
 *  it to a non-static value). The runtime cost is one short allocation
 *  per artifact write.
 * 
 *  `duration_ms` and `byte_length` use `#[specta(type = Number<u64>)]`
 *  to opt out of specta's bigint guard: both stay well under
 *  `Number.MAX_SAFE_INTEGER` (2^53) for any plausible recording
 *  (duration in ms maxes at ~285,000 years; byte length is bounded by
 *  the filesystem).
 */
export type RecordingArtifact = {
	id: string,
	durationMs: number,
	byteLength: number,
	mimeType: string,
};

export type SignalResult = {
	success: boolean,
	message: string,
};

/**
 *  Engine-tagged request body. JS serializes one of these as the `config`
 *  JSON argument on the `transcribe_recording` command. Wire tags match
 *  the FE settings (`transcription.service`): `whispercpp` / `parakeet` /
 *  `moonshine`.
 * 
 *  `pub` + `specta::Type` so the JS side gets the discriminated union as
 *  a typed argument via the `tauri-specta` generator. The existing serde
 *  tag + rename attributes carry through.
 */
export type TranscribeRequest = { engine: "whispercpp"; modelPath: string; language?: string | null; initialPrompt?: string | null } | { engine: "parakeet"; modelPath: string } | { engine: "moonshine"; modelPath: string; variant: MoonshineVariantWire };

export type TranscriptionError = { name: "AudioReadError"; message: string } | { name: "GpuError"; message: string } | { name: "ModelLoadError"; message: string } | { name: "TranscriptionError"; message: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

